services:
    mongodb:
        image: 'mongo:7.0.12'
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
